# Use the official Python image from the Docker Hub
FROM python:3.9-slim

# Set the working directory inside the Docker image
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 5000 to the outside
EXPOSE 5000

# Define environment variable
ENV FLASK_APP=app.py

# Command to run the application
CMD ["flask", "run", "--host=0.0.0.0"]
